### ISSUE TITLE
Opening Report and Presentation

### ISSUE THREAD

**Issue by DeriZSY** [Henrycobaltech/SUSTechLambda#9]
# Task List 
- [x] Class Diagram, Database Schema @binalloy 
- [x] Architecture, API @Henrycobaltech 
- [x] Presentation Slides @DennielZhang
- [x] Project Report @RainyTong @DeriZSY 

# Project Proposal (report & presentation)
1. Project title
2. Abstract (50-200 words)
3. Descriptions

# Proposal Requirements 
* Project Definition 
* Functional Requirements 
* Project Feature
  * Architecture: block diagram, flow charts, class diagram, database schema
  * Technology Stack
* Timeline: key dates, effort required in the number of hours, roles
